# Generated by Django 3.0.3 on 2020-06-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200530_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
